os: linux
dist: bionic
language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt -I
  - pip install -r test-requirements.txt -I
  - pip install . -I
#script: nosetests -P
